# Generated by Django 3.1.3 on 2020-12-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('map', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='propertysize',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertysize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.size'),
        ),
        migrations.AddField(
            model_name='propertysafety',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertysafety',
            name='safety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.safety'),
        ),
        migrations.AddField(
            model_name='propertyrule',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyrule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.rule'),
        ),
        migrations.AddField(
            model_name='propertyfacility',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.facility'),
        ),
        migrations.AddField(
            model_name='propertyfacility',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.attribute'),
        ),
        migrations.AddField(
            model_name='propertyattribute',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='attribute',
            field=models.ManyToManyField(through='property.PropertyAttribute', to='property.Attribute'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.country'),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.district'),
        ),
        migrations.AddField(
            model_name='property',
            name='facility',
            field=models.ManyToManyField(through='property.PropertyFacility', to='property.Facility'),
        ),
        migrations.AddField(
            model_name='property',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.host'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertyimage'),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.province'),
        ),
        migrations.AddField(
            model_name='property',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.refund'),
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.ManyToManyField(through='property.PropertySize', to='property.Size'),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.street'),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.type'),
        ),
        migrations.AddField(
            model_name='comment',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.host'),
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.review'),
        ),
    ]
