# Generated by Django 3.1.3 on 2020-12-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.country'),
        ),
        migrations.AddField(
            model_name='propertysizes',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertysizes',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.size'),
        ),
        migrations.AddField(
            model_name='propertysafeties',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertysafeties',
            name='safety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.safety'),
        ),
        migrations.AddField(
            model_name='propertyrules',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyrules',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.rule'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyfacilities',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.facility'),
        ),
        migrations.AddField(
            model_name='propertyfacilities',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyattributes',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.attribute'),
        ),
        migrations.AddField(
            model_name='propertyattributes',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='attribute',
            field=models.ManyToManyField(through='property.PropertyAttributes', to='property.Attribute'),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.category'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.country'),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.district'),
        ),
        migrations.AddField(
            model_name='property',
            name='facility',
            field=models.ManyToManyField(through='property.PropertyFacilities', to='property.Facility'),
        ),
        migrations.AddField(
            model_name='property',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.host'),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.province'),
        ),
        migrations.AddField(
            model_name='property',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.refund'),
        ),
        migrations.AddField(
            model_name='property',
            name='rule',
            field=models.ManyToManyField(through='property.PropertyRules', to='property.Rule'),
        ),
        migrations.AddField(
            model_name='property',
            name='safety',
            field=models.ManyToManyField(through='property.PropertySafeties', to='property.Safety'),
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.ManyToManyField(through='property.PropertySizes', to='property.Size'),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.type'),
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.city'),
        ),
        migrations.AddField(
            model_name='comment',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.host'),
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.review'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.province'),
        ),
    ]
