# Generated by Django 3.1.3 on 2020-12-04 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20201204_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_image',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
            preserve_default=False,
        ),
    ]
