# Generated by Django 3.1.3 on 2020-12-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20201204_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=1000),
        ),
    ]
