# Generated by Django 3.1.3 on 2020-12-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20201203_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.RemoveField(
            model_name='street',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='street',
            name='longitude',
        ),
        migrations.AddField(
            model_name='property',
            name='rule',
            field=models.ManyToManyField(through='property.PropertyRules', to='property.Rule'),
        ),
        migrations.AddField(
            model_name='property',
            name='safety',
            field=models.ManyToManyField(through='property.PropertySafeties', to='property.Safety'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterModelTable(
            name='propertyrules',
            table='property_rules',
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.category'),
            preserve_default=False,
        ),
    ]
