# Generated by Django 3.1.3 on 2020-12-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20201204_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rule',
            field=models.ManyToManyField(through='property.PropertyRules', to='property.Rule'),
        ),
        migrations.AddField(
            model_name='property',
            name='safty',
            field=models.ManyToManyField(through='property.PropertySafeties', to='property.Safety'),
        ),
    ]
