# Generated by Django 3.1.3 on 2020-12-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20201205_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='safty',
            new_name='safety',
        ),
    ]
