# Generated by Django 3.1.3 on 2020-12-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20201205_1448'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propertyrules',
            table='property_rules',
        ),
    ]
