# Generated by Django 3.1.3 on 2020-12-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20201205_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Street',
        ),
    ]
